name: issue-lint
on:
  issues:
    types: [opened]

jobs:
  template:
    runs-on: ubuntu-latest
    steps:
    - uses: powercord-community/suggestions/lint-action@master
      with:
        gh-token: ${{ secrets.GITHUB_TOKEN }}
